2020-01-22 15:25:32,258 ERROR: Exception on /login [GET] [in c:\users\mikoloth\ideaprojects\microblogmikko\venv\lib\site-packages\flask\app.py:1890]
Traceback (most recent call last):
  File "c:\users\mikoloth\ideaprojects\microblogmikko\venv\lib\site-packages\flask\app.py", line 2446, in wsgi_app
    response = self.full_dispatch_request()
  File "c:\users\mikoloth\ideaprojects\microblogmikko\venv\lib\site-packages\flask\app.py", line 1951, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "c:\users\mikoloth\ideaprojects\microblogmikko\venv\lib\site-packages\flask\app.py", line 1820, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "c:\users\mikoloth\ideaprojects\microblogmikko\venv\lib\site-packages\flask\_compat.py", line 39, in reraise
    raise value
  File "c:\users\mikoloth\ideaprojects\microblogmikko\venv\lib\site-packages\flask\app.py", line 1949, in full_dispatch_request
    rv = self.dispatch_request()
  File "c:\users\mikoloth\ideaprojects\microblogmikko\venv\lib\site-packages\flask\app.py", line 1935, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "C:\Users\Mikoloth\IdeaProjects\microblogmikko\app\routes.py", line 67, in login
    return render_template('login.html', title='Sign In', form=form)
  File "c:\users\mikoloth\ideaprojects\microblogmikko\venv\lib\site-packages\flask\templating.py", line 137, in render_template
    return _render(
  File "c:\users\mikoloth\ideaprojects\microblogmikko\venv\lib\site-packages\flask\templating.py", line 120, in _render
    rv = template.render(context)
  File "c:\users\mikoloth\ideaprojects\microblogmikko\venv\lib\site-packages\jinja2\asyncsupport.py", line 76, in render
    return original_render(self, *args, **kwargs)
  File "c:\users\mikoloth\ideaprojects\microblogmikko\venv\lib\site-packages\jinja2\environment.py", line 1008, in render
    return self.environment.handle_exception(exc_info, True)
  File "c:\users\mikoloth\ideaprojects\microblogmikko\venv\lib\site-packages\jinja2\environment.py", line 780, in handle_exception
    reraise(exc_type, exc_value, tb)
  File "c:\users\mikoloth\ideaprojects\microblogmikko\venv\lib\site-packages\jinja2\_compat.py", line 37, in reraise
    raise value.with_traceback(tb)
  File "C:\Users\Mikoloth\IdeaProjects\microblogmikko\app\templates\login.html", line 2, in <module>
    {% import 'bootstrap/wtf.html' as wtf %}
  File "c:\users\mikoloth\ideaprojects\microblogmikko\venv\lib\site-packages\jinja2\environment.py", line 1005, in render
    return concat(self.root_render_func(self.new_context(vars)))
  File "C:\Users\Mikoloth\IdeaProjects\microblogmikko\app\templates\login.html", line 17, in root
  File "C:\Users\Mikoloth\IdeaProjects\microblogmikko\app\templates\base.html", line 14, in root
    <span class="icon-bar"></span>
  File "C:\Users\Mikoloth\AppData\Local\Programs\Python\Python38-32\lib\site-packages\flask_bootstrap\templates\bootstrap\base.html", line 10, in root
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
  File "C:\Users\Mikoloth\AppData\Local\Programs\Python\Python38-32\lib\site-packages\flask_bootstrap\templates\bootstrap\base.html", line 20, in block_doc
    {% block body -%}
  File "C:\Users\Mikoloth\AppData\Local\Programs\Python\Python38-32\lib\site-packages\flask_bootstrap\templates\bootstrap\base.html", line 39, in block_html
  File "C:\Users\Mikoloth\AppData\Local\Programs\Python\Python38-32\lib\site-packages\flask_bootstrap\templates\bootstrap\base.html", line 90, in block_body
  File "C:\Users\Mikoloth\IdeaProjects\microblogmikko\app\templates\base.html", line 44, in block_navbar
    </li>
  File "c:\users\mikoloth\ideaprojects\microblogmikko\venv\lib\site-packages\jinja2\runtime.py", line 262, in call
    return __obj(*args, **kwargs)
  File "c:\users\mikoloth\ideaprojects\microblogmikko\venv\lib\site-packages\flask\helpers.py", line 370, in url_for
    return appctx.app.handle_url_build_error(error, endpoint, values)
  File "c:\users\mikoloth\ideaprojects\microblogmikko\venv\lib\site-packages\flask\app.py", line 2215, in handle_url_build_error
    reraise(exc_type, exc_value, tb)
  File "c:\users\mikoloth\ideaprojects\microblogmikko\venv\lib\site-packages\flask\_compat.py", line 39, in reraise
    raise value
  File "c:\users\mikoloth\ideaprojects\microblogmikko\venv\lib\site-packages\flask\helpers.py", line 357, in url_for
    rv = url_adapter.build(
  File "c:\users\mikoloth\ideaprojects\microblogmikko\venv\lib\site-packages\werkzeug\routing.py", line 2020, in build
    raise BuildError(endpoint, values, method, self)
werkzeug.routing.BuildError: Could not build url for endpoint 'main.index'. Did you mean 'index' instead?
2020-01-22 15:29:23,661 INFO: Microblog startup [in C:\Users\Mikoloth\IdeaProjects\microblogmikko\app\__init__.py:46]
2020-01-22 15:31:35,242 INFO: Microblog startup [in C:\Users\Mikoloth\IdeaProjects\microblogmikko\app\__init__.py:46]
2020-01-22 15:33:09,851 INFO: Microblog startup [in C:\Users\Mikoloth\IdeaProjects\microblogmikko\app\__init__.py:46]
2020-01-22 15:33:17,756 ERROR: Exception on / [GET] [in c:\users\mikoloth\ideaprojects\microblogmikko\venv\lib\site-packages\flask\app.py:1890]
Traceback (most recent call last):
  File "c:\users\mikoloth\ideaprojects\microblogmikko\venv\lib\site-packages\flask\app.py", line 2446, in wsgi_app
    response = self.full_dispatch_request()
  File "c:\users\mikoloth\ideaprojects\microblogmikko\venv\lib\site-packages\flask\app.py", line 1951, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "c:\users\mikoloth\ideaprojects\microblogmikko\venv\lib\site-packages\flask\app.py", line 1820, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "c:\users\mikoloth\ideaprojects\microblogmikko\venv\lib\site-packages\flask\_compat.py", line 39, in reraise
    raise value
  File "c:\users\mikoloth\ideaprojects\microblogmikko\venv\lib\site-packages\flask\app.py", line 1949, in full_dispatch_request
    rv = self.dispatch_request()
  File "c:\users\mikoloth\ideaprojects\microblogmikko\venv\lib\site-packages\flask\app.py", line 1935, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "c:\users\mikoloth\ideaprojects\microblogmikko\venv\lib\site-packages\flask_login\utils.py", line 261, in decorated_view
    return func(*args, **kwargs)
  File "C:\Users\Mikoloth\IdeaProjects\microblogmikko\app\routes.py", line 41, in index
    return render_template('index.html', title='Home', form=form, posts=posts.items, next_url=next_url, prev_url=prev_url)
  File "c:\users\mikoloth\ideaprojects\microblogmikko\venv\lib\site-packages\flask\templating.py", line 137, in render_template
    return _render(
  File "c:\users\mikoloth\ideaprojects\microblogmikko\venv\lib\site-packages\flask\templating.py", line 120, in _render
    rv = template.render(context)
  File "c:\users\mikoloth\ideaprojects\microblogmikko\venv\lib\site-packages\jinja2\asyncsupport.py", line 76, in render
    return original_render(self, *args, **kwargs)
  File "c:\users\mikoloth\ideaprojects\microblogmikko\venv\lib\site-packages\jinja2\environment.py", line 1008, in render
    return self.environment.handle_exception(exc_info, True)
  File "c:\users\mikoloth\ideaprojects\microblogmikko\venv\lib\site-packages\jinja2\environment.py", line 780, in handle_exception
    reraise(exc_type, exc_value, tb)
  File "c:\users\mikoloth\ideaprojects\microblogmikko\venv\lib\site-packages\jinja2\_compat.py", line 37, in reraise
    raise value.with_traceback(tb)
  File "C:\Users\Mikoloth\IdeaProjects\microblogmikko\app\templates\index.html", line 1, in <module>
    {% extends "base.html" %}
  File "c:\users\mikoloth\ideaprojects\microblogmikko\venv\lib\site-packages\jinja2\environment.py", line 1005, in render
    return concat(self.root_render_func(self.new_context(vars)))
  File "C:\Users\Mikoloth\IdeaProjects\microblogmikko\app\templates\index.html", line 14, in root
    <li class="previous{% if not prev_url %} disabled{% endif %}">
  File "C:\Users\Mikoloth\IdeaProjects\microblogmikko\app\templates\base.html", line 14, in root
    <span class="icon-bar"></span>
  File "C:\Users\Mikoloth\AppData\Local\Programs\Python\Python38-32\lib\site-packages\flask_bootstrap\templates\bootstrap\base.html", line 10, in root
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
  File "C:\Users\Mikoloth\AppData\Local\Programs\Python\Python38-32\lib\site-packages\flask_bootstrap\templates\bootstrap\base.html", line 20, in block_doc
    {% block body -%}
  File "C:\Users\Mikoloth\AppData\Local\Programs\Python\Python38-32\lib\site-packages\flask_bootstrap\templates\bootstrap\base.html", line 39, in block_html
  File "C:\Users\Mikoloth\AppData\Local\Programs\Python\Python38-32\lib\site-packages\flask_bootstrap\templates\bootstrap\base.html", line 92, in block_body
  File "C:\Users\Mikoloth\IdeaProjects\microblogmikko\app\templates\base.html", line 80, in block_content
  File "C:\Users\Mikoloth\IdeaProjects\microblogmikko\app\templates\index.html", line 33, in block_app_content
  File "c:\users\mikoloth\ideaprojects\microblogmikko\venv\lib\site-packages\jinja2\environment.py", line 430, in getattr
    return getattr(obj, attribute)
jinja2.exceptions.UndefinedError: 'wtf' is undefined
2020-01-22 15:40:20,871 INFO: Microblog startup [in C:\Users\Mikoloth\IdeaProjects\microblogmikko\app\__init__.py:46]
2020-01-23 13:32:05,785 INFO: Microblog startup [in C:\Users\Mikoloth\IdeaProjects\microblogmikko\app\__init__.py:48]
2020-01-23 14:49:45,028 INFO: Microblog startup [in C:\Users\Mikoloth\IdeaProjects\microblogmikko\app\__init__.py:48]
2020-01-23 15:33:13,108 INFO: Microblog startup [in C:\Users\Mikoloth\IdeaProjects\microblogmikko\app\__init__.py:52]
2020-01-23 16:37:01,401 INFO: Microblog startup [in C:\Users\Mikoloth\IdeaProjects\microblogmikko\app\__init__.py:52]
2020-01-23 16:37:44,734 INFO: Microblog startup [in C:\Users\Mikoloth\IdeaProjects\microblogmikko\app\__init__.py:52]
